# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inkdocument',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='ink_documents_thumbnails'),
        ),
    ]
