# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171115_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='inkdocumentannotation',
            name='ink_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.InkDocument'),
            preserve_default=False,
        ),
    ]
